# Server Configuration


# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=postgres
spring.datasource.password=december25
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
# Fix lazy loading issues
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true


# File Upload Configuration

spring.servlet.multipart.enabled=true
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=file:./src/main/resources/keystore.p12
server.ssl.key-store-password=december25
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
# JSON Configuration
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Africa/Lagos

# Static Resources
spring.mvc.static-path-pattern=/**

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.inkFront.schoolManagement=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# SMS Configuration
sms.provider=africastalking  
sms.username=sandbox
sms.apiKey=atsk_4588f8736f2ab2e88b0979ee147fc4895753653361566fa81721865f7e4fc8e2ece5a9ba
sms.fromNumber=+234XXXXXXXXXX
sms.enabled=true
africastalking.api.key=your_api_key_here
africastalking.username=sandbox
africastalking.sender.id=FaithFoundation
# Upload paths
upload.path.students=./uploads/students/
upload.path.teachers=./uploads/teachers/

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 hours in milliseconds
application.security.jwt.expiration=86400000
# 7 days in milliseconds
application.security.jwt.refresh-token.expiration=604800000

# Gmail SMTP SSL
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps

spring.mail.username=ogboholisa@gmail.com
spring.mail.password=rfzvsxwbjhdjzymj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# application.properties
# Africa's Talking

# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.web.resources.add-mappings=true



app.frontend-url=https://localhost:3000

# File upload configuration
file.upload-dir=./uploads


# Base URL for file access
app.base-url=https://localhost:8443
# Remove the old properties
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true